### ISSUE TITLE
__init__ methods should type-check context

### ISSUE THREAD

**Issue by tjprescott** [Microsoft/knack#13]
As I do the conversion work, I ran into a situation where there are two commands, one which has a context of type CLI and another CLICommandsLoader.  Since I don't know what context it is truly intended to have, I don't know which is correct and which is wrong. 

Especially given that "context" is such a nebulous term, this type check should really be in place to ensure the framework is used correctly.

**Comment by tjprescott** [comment]
Additionally (or maybe alternatively?) it might make sense to rename "ctx" to something that described what the context is supposed to be (i.e. cli, loader, etc.).  I would still recommend the type checking though.

**Comment by derekbekoe** [comment]
`ctx` should be the `CLI()` object you create in your CLI.
But really the aim here is to use the duck-typing convention in Python - ["If it walks like a duck and it quacks like a duck, then it must be a duck."](https://en.wikipedia.org/wiki/Duck_typing).

Have code like this goes against duck-typing.
```
if not isinstance(ctx, CLI):
    raise Exception(...)
```

**Comment by tjprescott** [comment]
There are a couple issues with this:

1) "context" is a vague term and in no way self-documenting. In Android, context may refer to Activities, Services, Applications, etc. but in knack it always refers to a CLI object. Thus, I would argue it should be called "cli" (in fact, in all of our code I call it "cli_ctx" for clarity). Sometimes vague terms are needed. Parent is inherently vague (although less so than context) because it could be many things. So making the name self-documenting would improve the usability from a developer perspective.

2) Since there's only one acceptable type for context, supplying anything else will yield an error (probably an AttributeError). This is completely not helpful to a developer who is unsure what to pass for "ctx". I recommend the type check because then at least you can clearly steer them in the right direction.

As this is a framework, I would place much higher value on making the framework easy for developers to use over being svelte, beautifully Pythonic code. A type check that clearly says "TypeError: Expected type CLI for parameter 'ctx': got CommandsLoader" would save me the developer far more time than "AttributeError: CommandsLoader doesn't have the attribute 'foo'".

**Comment by derekbekoe** [comment]
@tjprescott I can see `ctx` being confusing.

So I can change the name to be `cli_ctx` for more clarity.
Is that enough or you'd like to see the type checking also?

**Comment by derekbekoe** [comment]
... Or is type checking enough with the name still being `ctx`?
This would be less of a breaking change for anyone who currently uses knack.

**Comment by tjprescott** [comment]
If you only did one, I would suggest the explicit type check because the message can be made more helpful. I think "cli_ctx" is pretty clear, but if you passed it something else you'd still get the vague error, so I think the explicit check is preferable (though in a perfect world--both!)
