### ISSUE TITLE
Shouldn't have to subclass CLIHelp to customize privacy_statement and welcome_message

### ISSUE THREAD

**Issue by tjprescott** [Microsoft/knack#14]
As shown in the example (and what I actually had to do) to customize these messages you have to create a help class that inherits from CLIHelp and sets these parameters. It seems I should be able to pass these into CLI init, which would not require me to create this derived class.

**Comment by derekbekoe** [comment]
I can certainly see a use case for that but then what do you include in __init__ and what do you leave out? I didn't want the main CLI __init__ to be a long list of every thing that can be configured.

**Comment by tjprescott** [comment]
An alternative would be to pass in a CLIHelp object instead of a CLI help class.  Thus you'd configure the help object by instantiating it with the right messages, and then pass that into the CLI object.

**Comment by derekbekoe** [comment]
The constructor for `CLIHelp` requires `ctx` which you wouldn't have before the CLI object has been created (as that is the `ctx`).

I could create some `CLIHelpConfiguration` class that you can pass like this:
```Python
help_config = CLIHelpConfiguration(welcome_message='Hello world!')
CLI(help_config=help_config)
```

But then if someone does `CLI(help_config=my_help_config, help_cls=my_help_class)` the result could be ambiguous as your help class can have it's own configuration.

I see the class method as easily extensible as you desire.
```
class MyCLIHelp(CLIHelp):

    def __init__(self, ctx=None):
        super(MyCLIHelp, self).__init__(ctx=ctx,
                                        privacy_statement='My privacy statement.',
                                        welcome_message=WELCOME_MESSAGE)
``` 

Now I could add `privacy_statement` and `welcome_message` as kwargs to `CLI()` but next time a new field needs to be added to help, we have to keep on adding to `CLI()` kwargs.

**Comment by tjprescott** [comment]
> I can certainly see a use case for that but then what do you include in init and what do you leave out? I didn't want the main CLI init to be a long list of every thing that can be configured.

I get that 100%.  But if you think about it "welcome message" and "privacy statement" can very naturally be thought of as properties of the CLI (even though they are modeled as properties of the help system).  In this case, I would argue in favor of making them optional kwargs.

The most complex case (us) requires creating a subclass only to set these two strings.  The least complex case (anyone else) *still* requires creating a subclass to set just those two strings!

If there were an event called when the help system __init__ finished, then I could attach code setting those strings to that event to set those strings. That would be another approach that 1) wouldn't require a custom help class and 2) wouldn't add to the kwargs, so that might be a better option.  Thoughts?

**Comment by derekbekoe** [comment]
> The most complex case (us) requires creating a subclass only to set these two strings. The least complex case (anyone else) still requires creating a subclass to set just those two strings!

This is intended as then there's *one* way to do it.

The event could work but:
- Now you have 2 ways (either subclass or use event)
- You then have to register for the event right after you create the `CLI()` and before you call `cli.invoke()` as that's when the help object is created.
- It would look something like this...
```Python
def event_handler(ctx, help_config):
    help_config.privacy_statement='My privacy statement.'
    help_config.welcome_message='My welcome message'

self.ctx.register_event('Help.OnConfigure', event_handler)
```

**Comment by tjprescott** [comment]
I think this can be closed as, give the other changes you've made in 0.3.0, there's a lot more flexibility in a Help subclass that this would make sense.
