### ISSUE TITLE
Should be able to pass Custom CommandInvoker class to CLI

### ISSUE THREAD

**Issue by tjprescott** [Microsoft/knack#15]

**Comment by tjprescott** [comment]
If you run any commands that return a list, you'll get
```
{
  "currentPage": [],
  "nextLink": ""
}
```

You have to subclass CommandInvoker and largely clone this logic in order to make it work with lists. It would be better to have some kind of hook method that could be passed in or at least overwritten in the subclass in order to provide this handling without having to duplicate the core logic.

**Comment by tjprescott** [comment]
Actually, you can't even subclass the Invoker.  I had to monkey patch over it.

**Comment by tjprescott** [comment]
Additionally, the Knack invoker has no support for validators, so I need to monkey patch the CommandInvoker.execute method to reintroduce this functionality.

**Comment by derekbekoe** [comment]
You can pass in your own Command Invoker [here](https://github.com/Microsoft/knack/blob/master/knack/cli.py#L35). With this, you shouldn't have to clone a lot of the code.

Also, support for validators was added in https://github.com/Microsoft/knack/pull/21.

Closing but let me know if there is still are large block of code you have to clone just for a small change.
