### ISSUE TITLE
Handle input() function securely in Python 3

### ISSUE THREAD

**Issue by atbagga** [microsoft/knack#157]
https://stackoverflow.com/questions/31175820/simple-explanation-of-security-issues-related-to-input-vs-raw-input?noredirect=1&lq=1

**Comment by Ronkiro** [comment]
This is questionable, Python 3 uses "input" the same way as "raw_input"

https://snyk.io/blog/python-2-vs-3-security-differences/

I think the best way to solve those problems, while giving compatibility to Python 2 and Python 3, is to do something to check the python version, if 2, uses raw_input, else uses input.

We can mantain it with a simple snippet like this one:
```
try:
    input = raw_input
except NameError:
    pass

**Comment by atbagga** [comment]
This issue is not applicable since imports the input function from six.moves which handles the python2 and python3 compat input function appropriately by using raw_input in python 2 and input function in python 3 which are secure. 

Closing the issue as no action needs to be taken.

**Comment by atbagga** [comment]
Refer documentation here - https://pythonhosted.org/six/
