### ISSUE TITLE
Preview message is written to StdErr which causes scripts using the preview message fail in pipelines

### ISSUE THREAD

**Issue by atbagga** [microsoft/knack#166]
![image](https://user-images.githubusercontent.com/11888714/66228603-770d8580-e6fd-11e9-82ce-0db56489083c.png)

Reported on Azure-Devops extension - https://github.com/Azure/azure-devops-cli-extension/issues/811

**Comment by atbagga** [comment]
@yugangw-msft Can you please ask someone to take a look.

**Comment by jiasli** [comment]
Writing to std.err is a very common behavior across many CLI tools. 

The CI should not rely on the contents in std.err. The CI should check the exit code instead: https://github.com/Azure/azure-cli#exit-codes

**Comment by sebastianrogers** [comment]
Whether it is common does not make it correct.

A warning is not an error it is information.

The decision on how the pipeline should handle warnings, as distinct from errors, has now been removed. 

Azure pipelines, Microsoft's public CLI tool treats any output on STDERR as an Error.

Can you amend the tool to write Warnings, information and debug out to an appropriate stream so that when a developer raises a warning via your tool it is identifiable as a warning and not an error.

To assume and imply that there is no distinction between a warning and an error is not a valid assumption and not a common use of the terms.

Cheers

**Comment by pmatthews05** [comment]
I have had the same issue with warnings in pipelines. Latest one I've had a problem with was with the Storage account, that the name is going to change from StorageV2 to Storage 

`az : WARNING: The default kind for created storage account will change to 'StorageV2' from 'Storage' in future`

It doesn't matter if you set the name to Storage or StorageV2, this warning comes up every time and breaks the pipeline. 

I have reported it here:
[Developer Community Visual Studio](https://developercommunity.visualstudio.com/content/problem/752118/az-cli-reports-warnings-that-breaks-releases.html)

I've been told that they can replicate the issue and the ticket has been moved to the product team.

**Comment by atbagga** [comment]
@jiasli How about having a suppress warning (--suppress-warning) flag in the command? This can be a global parameter and framework should handle not putting warnings in case the flag is specified. 

This way users will know when they are taking dependency on a preview command and can explicitly suppress warnings in the scripts if they do not want the noise in the output. 

@sebastianrogers @pmatthews05 What do you  guys think? Will this be a reasonable option for fixing the issue.

**Comment by sebastianrogers** [comment]
I don't like this option as it is negating a negation.  It would be best if only errors were output to the error output.

We are looking at a wrapper function in PowerShell to handle it at the moment, typing this from memory so may have the odd typo.

function Invoke-AzCommand() {
param(
  # The command to execute
  [string]
  $Command
)

$LastErrorActionPreference = $ErrorActionPreference
$ErrorActionPreference = 'Continue'
Invoke-Expression -Command:$Command
$ExitCode = $LastExitCode
$ErrorActionPreference = $LastErrorActionPreference
switch ($ExitCode) {
  0 {}
  default {
    Write-Error -Message:$ExitCode
  }
}
}

**Comment by jiasli** [comment]
`stderr` is never designed only for errors. Please see https://unix.stackexchange.com/questions/331611/do-progress-reports-logging-information-belong-on-stderr-or-stdout

Please find the solution at https://github.com/Azure/azure-devops-cli-extension/issues/811#issuecomment-538901591

**Comment by sebastianrogers** [comment]
Been doing some reading and https://www.gnu.org/software/libc/manual/html_node/Standard-Streams.html seems to be the definitive link.

> Variable: FILE * stderr
The standard error stream, which is used for error messages and diagnostics issued by the program.

So it looks like it depends on if you catagorise a warning as a diagnostic, which grammatically I would not, but it does imply that similarly if a verbose or debug output was requested then the logging should definitely put it out on STD_ERR! 

Based on this it does appear that the script above for PowerShell or for Bash something like exec 2>&1 before the az command will be required.

**Comment by jiasli** [comment]
`2>&1` will pollute `stdout` where CLI writes result to. You may consider using `2>nul` or disabling `Fail on Standard Error` in the pipeline. `sys.stderr` is the default and valid place for Python's logging mechanism: https://docs.python.org/3.7/howto/logging.html

**Comment by jiasli** [comment]
We have added option `--only-show-errors` in https://github.com/microsoft/knack/pull/181 and also https://github.com/Azure/azure-cli/pull/12604 to disable warnings that are written to `stderr`. Knack [0.7.0rc1](https://pypi.org/project/knack/0.7.0rc1/) has already been released with this feature. Azure CLI will include it in [S167](https://github.com/Azure/azure-cli/milestone/84) release.
