### ISSUE TITLE
support experimental tag

### ISSUE THREAD

**Issue by yungezz** [microsoft/knack#175]
Request to add experimental tag, this is for Azure CLI usage. Azure CLI need this tag for new extension which is not stable yet, but under experimental. Experimental means CLI commands are in early experimental change, and targeting to change. It's used to get customer early feedback.

**Comment by yonzhan** [comment]
Planned in S167.

**Comment by jiasli** [comment]
Completed in https://github.com/microsoft/knack/pull/181.
