### ISSUE TITLE
Should be able to access the command loader and similar objects.

### ISSUE THREAD

**Issue by tjprescott** [Microsoft/knack#20]
Currently there is only a property on the CLI object for "command_loader_cls".  This makes it very difficult to access methods that require a command loader (for example, registering commands!).

**Comment by derekbekoe** [comment]
It's available through `ctx.invocation.commands_loader`.
The commands loader is created *per invocation*.
Therefore, it's on the invocation object that gets created when `CLI.invoke` is called.

- https://github.com/Microsoft/knack/blob/master/knack/cli.py#L120
- https://github.com/Microsoft/knack/blob/master/knack/invocation.py#L34

**Comment by derekbekoe** [comment]
Closing as I think this answers the query.
