### ISSUE TITLE
Release candidate tags are sorted as higher than actual releases (0.8.0rc2 >> 0.8.0)

### ISSUE THREAD

**Issue by bluca** [microsoft/knack#230]
Please use a ```~``` when appending ```rcX``` to a tag. All software that does version comparison will consider 0.8.0 as being lower/older than 0.8.0rc2.

```
$ dpkg --compare-versions 0.8.0 gt 0.8.0rc2 && echo "true" || echo "false"
false
$ dpkg --compare-versions 0.8.0 gt 0.8.0~rc2 && echo "true" || echo "false"
true
```

**Comment by jiasli** [comment]
`X.YrcN` is the correct format according to [PEP 440 Pre-releases](https://www.python.org/dev/peps/pep-0440/#pre-releases).

`0.8.0` is newer than `0.8.0rc2` in the Python world.

```py
>>> from packaging.version import Version
>>> Version("0.8.0") > Version("0.8.0rc2")
True
```

**Comment by bluca** [comment]
Maybe, but not in the rest of the world. dpkg, and probably rpm too, do not follow that custom rule.

**Comment by jiasli** [comment]
If we don't follow PEP 440, installation tools like `pip` will fail to install the correct version.

This issue has been discussed before: https://github.com/paylogic/py2deb/issues/8.

Also, according to [Debian New Maintainers' Guide / 2. First steps / 2.6. Package name and version](https://www.debian.org/doc/manuals/maint-guide/first.en.html#namever),

> Although this simple approach works most of the time, you may need to **adjust package name and upstream version** by renaming the upstream source to follow Debian Policy and existing convention.

Also see: [Versioning your Python project for Debian](https://overtag.dk/v2/blog/versioning-your-python-project/)

**Comment by bluca** [comment]
I know perfectly well that there are workarounds, and in fact I am already using them - but they are workarounds, not solutions, that create additional work downstream. Please consider using a scheme that works everywhere, regardless of what PEP440 says, given it's clearly incompatible with what the rest of the world does.

**Comment by jiasli** [comment]
> regardless of what PEP440 says

PEP 440 is the official spec of Python versioning. If we don't follow it but switch to Debian versioning, Python's libs will fail to recognize the version:

```py
>>> from packaging.version import Version
>>> Version("0.8.0~rc2")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\<name>\AppData\Local\Programs\Python\Python38\lib\site-packages\packaging\version.py", line 298, in __init__
    raise InvalidVersion("Invalid version: '{0}'".format(version))
packaging.version.InvalidVersion: Invalid version: '0.8.0~rc2'
```

You may open a discussion on https://discuss.python.org for PEP 440.

**Comment by bluca** [comment]
There are alternatives that work everywhere. For example, instead of ```0.8.0rc1``` you could use something like ```0.7.999rc1```. Then sorting works as expected with all tools.

**Comment by jiasli** [comment]
I understand your concern @bluca. However, as a Python tool, it would be better for us to follow the naming convention of Python community, like other Python tools do.

pip: https://pypi.org/project/pip/#history

![image](https://user-images.githubusercontent.com/4003950/105789869-268afd00-5fbe-11eb-98c2-4d534d349047.png)

numpy: https://pypi.org/project/numpy/#history

![image](https://user-images.githubusercontent.com/4003950/105789991-6356f400-5fbe-11eb-93a2-c303c8e74b0b.png)

PyYAML: https://pypi.org/project/PyYAML/#history

![image](https://user-images.githubusercontent.com/4003950/105790163-bcbf2300-5fbe-11eb-9acb-5e0866dbf271.png)

Thanks for the understanding.
