### ISSUE TITLE
Improve error related strings

### ISSUE THREAD

**Issue by samedder** [Microsoft/knack#31]
Not sure where's the best place to put this, but we would like a better way to capture 400 and 500 error responses from lower libraries like `urrllib3`. Right now on 500 responses we see the following unhelpful message accompanied by a stack-trace:

> Caused by ResponseError('too many 500 error responses',))

It would be nice if there was some callback we could register to handle these errors more gracefully

**Comment by derekbekoe** [comment]
This should be achievable by overriding `CLI. exception_handler` (https://github.com/Microsoft/knack/blob/master/knack/cli.py#L158).

It gets called if there's an unknown exception - https://github.com/Microsoft/knack/blob/master/knack/cli.py#L205.
