### ISSUE TITLE
ArgumentsContext register & register_alias are exactly the same

### ISSUE THREAD

**Issue by derekbekoe** [Microsoft/knack#41]
Consider removing one of them.

**Comment by tjprescott** [comment]
For that matter, both are essentially the same as "argument" which is the only one I use.  I'd consider removing both. Technically register_alias makes the option list a positional arg, so you don't have to type "option_list=" but it's kinda'   🤷‍♂️

**Comment by derekbekoe** [comment]
This was fixed in https://github.com/Microsoft/knack/commit/af674bfea793ff42ae31a381a21478bae4b71d7f
