### ISSUE TITLE
Missing telemetry or at least extensibility hooks to inject telemetry

### ISSUE THREAD

**Issue by tjprescott** [Microsoft/knack#7]
Azure CLI core contains telemetry that could theoretically be part of this repo. As it stands, the CLI has telemetry code build into various methods which means I can't convert those parts to this package without throwing away that customization.

**Comment by derekbekoe** [comment]
Closing as until we have specific parts of the code where we want to raise events, there's nothing actionable here.
Also, I think without any changes, Azure CLI was able to hook in its own telemetry.

**Comment by tjprescott** [comment]
Yes, but it did that by subclassing the hell out of things. :-P
