### ISSUE TITLE
[arguments.py] ValueError does not take keyword arguments

### ISSUE THREAD

**Issue by derekbekoe** [Microsoft/knack#70]
https://github.com/Microsoft/knack/blob/master/knack/arguments.py#L60

We should not call `ValueError` as a keyword argument.

Similar to https://github.com/Microsoft/knack/issues/60

**Comment by avirlrma** [comment]
@derekbekoe Hey! I like the issue, Can I start working on this?

**Comment by derekbekoe** [comment]
@avirlrma Yes absolutely.
Adding @tjprescott as FYI also.
