### ISSUE TITLE
Error message color does not have enough contrast with default console backgrounds

### ISSUE THREAD

**Issue by tedchamb** [Microsoft/knack#71]
The vsts cli is built on knack and we have received several customer complaints that the color of red used does not provide enough contrast with the standard console backgrounds, and is therefore hard to read.  Is it possible to adjust the default error message color to a brighter red that provides more contrast?  It would also be good to provide a mechanism for the consuming application to choose the colors.  This way we can implement a way customers can configure this in our application if they don't like the default.

Actual feedback from customer:
The error messages are printed in dark red. That's very hard to read. 
![example](https://user-images.githubusercontent.com/13457072/35584295-941f23a4-05c2-11e8-95d8-ea7fc64f40b2.png)

**Comment by invinciblycool** [comment]
@derekbekoe I would like to take this up.

**Comment by StingyJack** [comment]
The library should honor the hosting console's (the user's preferences) display colors and not choose an arbitrary color. 

This is an accessibility issue and should be given appropriate priority. It should really not be considered a feature request.

**Comment by StingyJack** [comment]
I made this change to my local repo, but am not sure how to go about testing it where I want to see the change ultimately effected.
![image](https://user-images.githubusercontent.com/15381181/52561896-b2ec8700-2dca-11e9-95a8-26dc3d712b1e.png)

Is there a script that will make a locally usable knack that I can use in a local copy of azure-cli, that i can then build and run?  Or should I just pip install the knack package into the azure-cli and edit there?

**Comment by tjprescott** [comment]
If you have cloned the repo, you should be able to go to the root of that repo and run `pip install -e <path to knack setup.py file> --ignore-installed`.

The other option would be to modify the code in you virtual environment's site-packages folder where you have the CLI installed.

**Comment by atbagga** [comment]
@StingyJack Here is the difference in the two colors (LIGHTRED_EX on top, RED at bottom) on windows command prompt. I also tried on powershell and the LIGHTRED_EX seems much better in contrast. 

![image](https://user-images.githubusercontent.com/11888714/56230989-fbf6db00-609a-11e9-9b39-7898b98c8b9d.png)

**Comment by tjprescott** [comment]
Fixed by PR #147.
