### ISSUE TITLE
Support for passing in JSON as text files

### ISSUE THREAD

**Issue by Christina-Kang** [Microsoft/knack#81]
Hello,

Is there currently any support for taking a file for JSON parameter inputs? If not, are there any plans for it? 
It's quite a pain to escape quotes, etc, when passing in JSON inputs in command line :) 

Thanks!

**Comment by tjprescott** [comment]
You should be able to load those files like so:
`blah... --my-json-param @json_file.json`

**Comment by tjprescott** [comment]
Prefix the filename with @

**Comment by samedder** [comment]
@tjprescott is there a specific version that we should be using now? I think we were on `0.1.1` for our CLI, any issues if we upgrade to the latest?

**Comment by tjprescott** [comment]
@samedder sorry, I thought this functionality was in Knack because it exists in the Azure CLI that Knack was based off of.  Currently this is not in Knack.

**Comment by parkerduckworth** [comment]
Hi,

I developed a fix to this issue, and have added a test for this fix to the testing suite. All tests are passing.
I have the input JSON file being loaded into the parameter as a dict.  Is this the desired behavior?  

Just wanted to make sure I'm accurately addressing the issue before submitting a PR.

**Comment by tjprescott** [comment]
Hi @parkerduckworth the implementation for the @ feature is already in the Azure CLI and would basically be lifted from that. It would essentially allow you to use `--my-param @some_file` to load the contents of that file _as a string_.  If the developer wanted to transform or interpret that string (say, as a dict or JSON object) that would do that either in their command logic or in a validator. 

https://github.com/Azure/azure-cli/blob/dev/src/azure-cli-core/azure/cli/core/commands/__init__.py#L64

Then it's simply a matter of having the main command flow call this at the appropriate time. Hope that clarifies things.

Thank you for your willingness to contribute!

**Comment by tjprescott** [comment]
This has been implemented in #142. Thanks @parkerduckworth! It will be in the next knack release.
