### ISSUE TITLE
Migration process and pain points

### ISSUE THREAD

**Issue by tjprescott** [Microsoft/knack#9]
I am working on converting just the Redis commands to use Knack.  The process, as best I can tell, is something like this:

1. wrap the contents of `commands.py` in a method `load_command_table`. Import this method in the CommandsLoader class in the `__init__.py` file.
2. wrap the contents of `params.py` in a method `load_arguments`. Import this method in the CommandsLoader class in the `__init__.py` file.

**For old style registration**
3a. Add `self.` to each `cli_command` entry
3b. Add `client_factory=` to every command because this is now a kwarg instead of a positional arg.
3c. Add `self.` to each `register_cli_argument` entry

**For new style registration**
3e. Replace any uses of `create_service_adapter` with a simple template string expected by Knack. 
3f. Add `self` as the 2nd parameter in each ServiceGroup entry. 
3g. Swap the template parameter and the client factory parameter (now 3rd and 4th).
3h. For each s.group call, add `self` as the second parameter.
3i. Custom commands, because they now require a separate client factory, must be broken out into separate ServiceGroups.
3j. More to come...

4. Add `cli_ctx` as an argument to the signature of all client factory methods and custom methods.
5. Update all references to `get_sdk` or `supported_api_version` to use `self.ctx`, the client's CLI reference.

**Comment by tjprescott** [comment]
Relative impacts:
1. Moderate. Requires that any changes made to a command's `command.py` fille be copied over to the new class.
2. Minimal.
3. Minimal.
4. Moderate. Requires that any changes made to a command's `params.py` file be copied over to the new class.
5. Minimal
6. Moderate. Starts getting into "Rebase Hell" territory.
7. Major.

**Comment by derekbekoe** [comment]
I've removed the milestone as I don't see anything actionable here but will continue to monitor this issue...
Some of the pain points are due to Knack not having a global application object that can just be imported directory like was the case in Azure CLI.

**Comment by tjprescott** [comment]
Very true. This need not be tied to any milestone. I am making some simplifications in the CLI that will likely be worth porting over into knack.

**Comment by derekbekoe** [comment]
Closing issue but still comments welcome / new issues can be created.
